# The context path under which all services will be available
quarkus.cxf.path = /

# Publish "VectorService" under the context path /${quarkus.cxf.path}/vector
quarkus.cxf.endpoint."/dvector".implementor=isos.isysiesd.dvimpl.DvectorImpl
 quarkus.cxf.endpoint."/dvector".logging.enabled = pretty

# Define the port for service dvector, being 0 value for random dynamic port
# If 0 is adopted, consider to use dynamic client binding
# following discovery in a service registry
quarkus.http.port = 8080
# quarkus.http.port = 0 for dynamic binding of multiple dvector running instances
