# Run gRPC on the same port as Quarkus HTTP.
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.server.enable-reflection-service=true
quarkus.http.http2=true

# Define the port for service calculator, being 0 value for random dynamic port
# If 0 is adopted, consider to use dynamic client binding
# following discovery in a service registry
quarkus.http.port = 0
# quarkus.http.port = 0 for dynamic binding of multiple calculator running instances

quarkus.http.host=0.0.0.0
